steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/django-crud-app', '.']
    env:
      - 'DB_USER=${_DB_USER}'
      - 'DB_PASSWORD=${_DB_PASSWORD}'
      - 'SECRET_KEY=${_SECRET_KEY}'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run --rm \
        -e DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/dbname \
        gcr.io/$PROJECT_ID/django-crud-app python manage.py test
    waitFor: ['Build Image']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Start Cloud SQL Auth Proxy'
    entrypoint: bash
    args:
      - '-c'
      - |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && \
        chmod +x cloud_sql_proxy && \
        ./cloud_sql_proxy -dir=/cloudsql -instances=$PROJECT_ID:REGION:INSTANCE_ID &
    waitFor: ['Build Image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image'
    args: ['push', 'gcr.io/$PROJECT_ID/django-crud-app']
    waitFor: ['Run Tests']

  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install bandit
        bandit -r . -f json -o bandit_report.json
        if grep -q '"issue_severity": "HIGH"' bandit_report.json; then
          echo 'Se encontraron problemas de alta severidad en Bandit'; exit 1;
        fi
    id: 'security-scan'
    
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to Cloud Run'
    args:
      - run
      - deploy
      - django-crud-app
      - --image=gcr.io/$PROJECT_ID/django-crud-app
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --add-cloudsql-instances=$PROJECT_ID:REGION:INSTANCE_ID
    waitFor: ['Push Image']

images:
  - gcr.io/$PROJECT_ID/django-crud-app

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-user/versions/latest
      env: _DB_USER
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: _DB_PASSWORD
    - versionName: projects/$PROJECT_ID/secrets/secret-key/versions/latest
      env: _SECRET_KEY
